# Generated by Django 3.1.7 on 2021-05-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('founded_on', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('head_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kurz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('description', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
